// packages/angular-components/projects/authing-guard/src/lib/authing-guard.component.ts
import { Component, OnInit } from '@angular/core'
import { AuthingGuard } from 'native-js'

@Component({
  selector: 'lib-AuthingGuard',
  template: ` <div id="authing_guard_container"></div> `,
  styles: [],
})
export class AuthingGuardComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}

  ngAfterViewInit() {
    const guard = new AuthingGuard('59f86b4832eb28071bdd9214', {
      target: '#root',

      apiHost: 'http://console.authing.localhost:3000',
      // loginMethods: Object.values(LoginMethods),
      logo:
        'https://files.authing.co/user-contents/photos/0a4c99ff-b8ce-4030-aaaf-584c807cb21c.png',
      title: 'Authing',
      // defaultLoginMethod: LoginMethods.LDAP,
      // registerMethods: Object.values(RegisterMethods),
      // defaultRegisterMethod: RegisterMethods.Email,
      defaultScenes: 'login',
      // socialConnections: Object.values(SocialConnections),
      // enterpriseConnections: ["oidc1"],
      appId: '5fa5053e252697ad5302ce7e',
      // autoRegister: true,
    })
  }
}

// packages/vue-components/src/components/AuthingGuard.vue
<template>
  <div id="authing_guard_container"></div>
</template>

<script>
import { AuthingGuard as NativeAuthingGuard } from 'native-js'

export default AuthingGuard = {
  name: 'AuthingGuard',
  mounted () {
    const guard = new NativeAuthingGuard('59f86b4832eb28071bdd9214', {
      target: '#authing_guard_container',

      apiHost: 'http://console.authing.localhost:3000',
      // loginMethods: Object.values(LoginMethods),
      logo:
        'https://files.authing.co/user-contents/photos/0a4c99ff-b8ce-4030-aaaf-584c807cb21c.png',
      title: 'Authing',
      // defaultLoginMethod: LoginMethods.LDAP,
      // registerMethods: Object.values(RegisterMethods),
      // defaultRegisterMethod: RegisterMethods.Email,
      defaultScenes: 'login',
      // socialConnections: Object.values(SocialConnections),
      // enterpriseConnections: ["oidc1"],
      appId: '5fa5053e252697ad5302ce7e',
      // autoRegister: true,
    })

    const evts = [
      'load',
      'load-error',
      'login',
      'login-error',
      'register',
      'register-error',
      'pwd-email-send',
      'pwd-email-send-error',
      'pwd-phone-send',
      'pwd-phone-send-error',
      'pwd-reset',
      'pwd-reset-error',
      'close',
    ]

    const listeners = evts.reduce((acc, evtName) => {
      return Object.assign({}, acc, {
        [evtName]: (...rest) => {
          this.$emit(evtName, ...rest)
        },
      })
    }, {})

    evts.forEach(evtName => guard.on(evtName, listeners[evtName]))
  },
}
</script>
