// packages/native-js/src/components/Guard/index.tsx
import React from "react";
import ReactDOM from "react-dom";
import { Guard as ReactAuthingGuard } from "@authing/react-ui-components";
import {
  User,
  GuardMode,
  GuardScenes,
  LoginMethods,
  getAuthClient,
  CommonMessage,
  initAuthClient,
  RegisterMethods,
  GuardEventsHandler,
  AuthenticationClient,
  GuardEventsHandlerKebab,
  GuardEventsCamelToKebabMap,
  AuthenticationClientOptions,
} from "@authing/react-ui-components";
import "@authing/react-ui-components/lib/index.min.css";
import {
  GuardComponentConfig,
  GuardLocalConfig,
} from "@authing/react-ui-components/components/Guard/config";
import { GuardEvents } from "@authing/react-ui-components/components/Guard/event";

export type {
  User,
  CommonMessage,
  GuardEventsHandler,
  AuthenticationClient,
  GuardEventsHandlerKebab,
  AuthenticationClientOptions,
};

export {
  GuardMode,
  GuardScenes,
  LoginMethods,
  getAuthClient,
  initAuthClient,
  RegisterMethods,
  GuardEventsCamelToKebabMap,
};

export type GuardEventListeners = {
  [key in keyof GuardEventsHandlerKebab]: Exclude<
    Required<GuardEventsHandlerKebab>[key],
    undefined
  >[];
};

export class Guard {
  constructor(
    private appId: string,
    private config?: Partial<GuardLocalConfig>
  ) {
    this.render();
  }

  static getGuardContainer(selector?: string | HTMLElement) {
    const defaultId = "authing_guard_container";

    if (!selector) {
      let container = document.querySelector(`#${defaultId}`);
      if (!container) {
        container = document.createElement("div");
        container.id = defaultId;
        document.body.appendChild(container);
      }

      return container;
    }

    if (typeof selector === "string") {
      return document.querySelector(selector);
    }

    return selector;
  }

  private visible = this.config?.mode === GuardMode.Modal ? false : true;

  private eventListeners = Object.values(GuardEventsCamelToKebabMap).reduce(
    (acc, evtName) => {
      return Object.assign({}, acc, {
        [evtName]: [],
      });
    },
    {} as GuardEventListeners
  );

  private render(cb?: () => void) {
    const evts: GuardEventsHandler = Object.entries(
      GuardEventsCamelToKebabMap
    ).reduce((acc, [reactEvt, nativeEvt]) => {
      return Object.assign({}, acc, {
        [reactEvt]: (...rest: any) => {
          if (nativeEvt === "close") {
            this.hide();
          }

          // TODO 返回最后一个执行函数的值，实际应该只让监听一次
          return (
            this.eventListeners[nativeEvt]
              // @ts-ignore
              .map((item: any) => {
                return item(...rest);
              })
              .slice(-1)[0] ?? true
          );
        },
      });
    }, {} as GuardEventsHandler);

    return ReactDOM.render(
      <ReactAuthingGuard
        {...(evts as GuardEvents)}
        appId={this.appId}
        config={this.config as GuardComponentConfig}
        visible={this.visible}
      />,
      Guard.getGuardContainer(this.config?.target),
      cb
    );
  }

  on<T extends keyof GuardEventsHandlerKebab>(
    evt: T,
    handler: Exclude<GuardEventsHandlerKebab[T], undefined>
  ) {
    this.eventListeners[evt]!.push(handler as any);
  }

  show() {
    this.visible = true;
    this.render();
  }

  hide() {
    this.visible = false;
    this.render();
  }
}

// packages/vue-components/src/components/Guard.vue
<template>
  <div id="authing_guard_container"></div>
</template>

<script>
import {
  getAuthClient,
  initAuthClient,
  Guard as NativeGuard,
  GuardEventsCamelToKebabMap,
  GuardMode,
  GuardScenes,
  LoginMethods,
  RegisterMethods,
} from "@authing/native-js-ui-components";
import "@authing/native-js-ui-components/lib/index.min.css";
import { Guard as NativeGuard } from "@authing/native-js-ui-components/lib/index.min.js";

export { getAuthClient, initAuthClient, GuardMode, GuardScenes, LoginMethods, RegisterMethods };

const format = (a, b) => {
  return !a || a === "false" ? b : true;
};

const callbackEvent = ["before-login", "before-register"];

export default {
  name: "Guard",
  props: {
    appId: {
      type: String,
      required: true,
    },
    config: {
      type: Object,
      required: false,
    },
    visible: {
      type: Boolean,
      default: false,
    },
    mode: {
      type: String,
      required: false, // normal(全屏) modal(弹窗)
    },
    autoRegister: {
      type: Boolean,
      required: false,
    },
    isSSO: {
      type: Boolean,
      required: false,
    },
    clickCloseable: {
      type: Boolean,
      default: true,
      required: false,
    },
    escCloseable: {
      type: Boolean,
      default: true,
      required: false,
    },
    onBeforeLogin: {
      type: Function,
      required: false,
    },
    onBeforeRegister: {
      type: Function,
      required: false,
    },
  },
  data() {
    return {
      localVisible: false,
      $guard: null,
    };
  },
  watch: {
    visible: {
      immediate: true,
      handler(val) {
        if (val !== this.localVisible) {
          this.localVisible = val;
        }
      },
    },
    localVisible: {
      handler(val) {
        if (val !== this.visible) {
          this.$emit("update:visible", val);
        }

        if (val) {
          this.show();
        } else {
          this.hide();
        }
      },
    },
  },
  mounted() {
    this.config = this.config || {};
    this.config.mode = this.mode ? this.mode : this.config.mode;
    this.config.autoRegister = this.autoRegister ? this.autoRegister : this.config.autoRegister;
    this.config.isSSO = this.isSSO ? this.isSSO : this.config.isSSO;
    this.config.clickCloseable = this.clickCloseable ? this.clickCloseable : this.config.clickCloseable;
    this.config.escCloseable = this.escCloseable ? this.escCloseable : this.config.escCloseable;

    // this.config.autoRegister = format(this.autoRegister, this.config.autoRegister)
    // this.config.isSSO = format(this.isSSO, this.config.isSSO)
    // this.config.clickCloseable = format(this.clickCloseable, this.config.clickCloseable)
    // this.config.escCloseable = format(this.escCloseable, this.config.escCloseable)

    const guard = new NativeGuard(this.appId, this.config);

    const evts = Object.values(GuardEventsCamelToKebabMap);
    const kebabToCamelMap = Object.entries(GuardEventsCamelToKebabMap).reduce((acc, [camel, kebab]) => {
      return Object.assign({}, acc, {
        [kebab]: camel,
      });
    }, {});

    const listeners = evts.reduce((acc, evtName) => {
      return Object.assign({}, acc, {
        [evtName]: (...rest) => {
          if (evtName === "close") {
            this.localVisible = false;
          }
          if (!callbackEvent.includes(evtName)) {
            this.$emit(evtName, ...rest);
          } else {
            const camelEvtName = kebabToCamelMap[evtName];

            if (this[camelEvtName]) {
              return this[camelEvtName](...rest);
            }
            return true;
          }
        },
      });
    }, {});

    evts.forEach((evtName) => guard.on(evtName, listeners[evtName]));

    if (this.localVisible) {
      guard.show();
    }
    this.$guard = guard;
  },
  methods: {
    show() {
      this.$guard.show();
    },
    hide() {
      this.$guard.hide();
    },
  },
};
</script>
