// packages/vue-components/src/components/AuthingGuard.vue
<template>
  <div id="authing_guard_container"></div>
</template>

<script>
import {
  getAuthClient,
  initAuthClient,
  AuthingGuard as NativeAuthingGuard,
  GuardEventsCamelToKebabMap,
  GuardMode,
  GuardScenes,
  LoginMethods,
  RegisterMethods,
} from '@authing/native-js-ui-components'
import '@authing/native-js-ui-components/lib/index.min.css'

export { getAuthClient, initAuthClient, GuardMode, GuardScenes, LoginMethods, RegisterMethods }

const format = (a, b) => {
  return !a || a === 'false' ? b : true
}

export default {
  name: 'AuthingGuard',
  props: {
    appId: {
      type: String,
      required: true,
    },
    config: {
      type: Object,
      required: false,
    },
    visible: {
      type: Boolean,
      default: false,
    },
    mode: {
      type: String,
      required: false, // normal(全屏) modal(弹窗)
    },
    autoRegister: {
      type: Boolean,
      required: false,
    },
    isSSO: {
      type: Boolean,
      required: false,
    },
    clickCloseable: {
      type: Boolean,
      required: true,
    },
    escCloseable: {
      type: Boolean,
      required: true,
    },
  },
  data() {
    return {
      localVisible: false,
      $guard: null,
    }
  },
  watch: {
    visible: {
      immediate: true,
      handler(val) {
        if (val !== this.localVisible) {
          this.localVisible = val
        }
      },
    },
    localVisible: {
      handler(val) {
        if (val !== this.visible) {
          this.$emit('update:visible', val)
        }

        if (val) {
          this.show()
        } else {
          this.hide()
        }
      },
    },
  },
  mounted() {
    this.config = this.config || {}
    this.config.mode = this.mode ? this.mode : this.config.mode
    this.config.autoRegister = this.autoRegister ? this.autoRegister : this.config.autoRegister
    this.config.isSSO = this.isSSO ? this.isSSO : this.config.isSSO
    this.config.clickCloseable = this.clickCloseable ? this.clickCloseable : this.config.clickCloseable
    this.config.escCloseable = this.escCloseable ? this.escCloseable : this.config.escCloseable

    // this.config.autoRegister = format(this.autoRegister, this.config.autoRegister)
    // this.config.isSSO = format(this.isSSO, this.config.isSSO)
    // this.config.clickCloseable = format(this.clickCloseable, this.config.clickCloseable)
    // this.config.escCloseable = format(this.escCloseable, this.config.escCloseable)

    const guard = new NativeAuthingGuard(this.appId, this.config)

    const evts = Object.values(GuardEventsCamelToKebabMap)

    const listeners = evts.reduce((acc, evtName) => {
      return Object.assign({}, acc, {
        [evtName]: (...rest) => {
          if (evtName === 'close') {
            this.localVisible = false
          }
          this.$emit(evtName, ...rest)
        },
      })
    }, {})

    evts.forEach((evtName) => guard.on(evtName, listeners[evtName]))

    if (this.localVisible) {
      guard.show()
    }
    this.$guard = guard
  },
  methods: {
    show() {
      this.$guard.show()
    },
    hide() {
      this.$guard.hide()
    },
  },
}
</script>

// packages/native-js/src/components/AuthingGuard/index.tsx
import React from 'react'
import ReactDOM from 'react-dom'
import { AuthingGuard as ReactAuthingGuard } from '@authing/react-ui-components'
import {
  User,
  GuardMode,
  UserConfig,
  GuardScenes,
  LoginMethods,
  getAuthClient,
  CommonMessage,
  initAuthClient,
  RegisterMethods,
  GuardEventsHandler,
  AuthenticationClient,
  GuardEventsHandlerKebab,
  GuardEventsCamelToKebabMap,
  AuthenticationClientOptions,
} from '@authing/react-ui-components'
import '@authing/react-ui-components/lib/index.min.css'

export type {
  User,
  UserConfig,
  CommonMessage,
  GuardEventsHandler,
  AuthenticationClient,
  GuardEventsHandlerKebab,
  AuthenticationClientOptions,
}

export {
  GuardMode,
  GuardScenes,
  LoginMethods,
  getAuthClient,
  initAuthClient,
  RegisterMethods,
  GuardEventsCamelToKebabMap,
}

export type EventListeners = {
  [key in keyof GuardEventsHandlerKebab]: Exclude<
    Required<GuardEventsHandlerKebab>[key],
    undefined
  >[]
}

export class AuthingGuard {
  constructor(private appId: string, private config?: UserConfig) {
    this.render()
  }

  static getGuardContainer(selector?: string | HTMLElement) {
    const defaultId = 'authing_guard_container'

    if (!selector) {
      let container = document.querySelector(`#${defaultId}`)
      if (!container) {
        container = document.createElement('div')
        container.id = defaultId
        document.body.appendChild(container)
      }

      return container
    }

    if (typeof selector === 'string') {
      return document.querySelector(selector)
    }

    return selector
  }

  private visible = this.config?.mode === GuardMode.Modal ? false : true

  private eventListeners = Object.values(GuardEventsCamelToKebabMap).reduce(
    (acc, evtName) => {
      return Object.assign({}, acc, {
        [evtName]: [],
      })
    },
    {} as EventListeners
  )

  private render(cb?: () => void) {
    const evts: GuardEventsHandler = Object.entries(
      GuardEventsCamelToKebabMap
    ).reduce((acc, [reactEvt, nativeEvt]) => {
      return Object.assign({}, acc, {
        [reactEvt]: (...rest: any) => {
          if (nativeEvt === 'close') {
            this.hide()
          }

          this.eventListeners[nativeEvt].forEach((item: any) => {
            return item(...rest)
          })          
        },
      })
    }, {} as GuardEventsHandler)

    return ReactDOM.render(
      <ReactAuthingGuard
        {...evts}
        appId={this.appId}
        config={this.config}
        visible={this.visible}
      />,
      AuthingGuard.getGuardContainer(this.config?.target),
      cb
    )
  }

  on<T extends keyof GuardEventsHandlerKebab>(
    evt: T,
    handler: Exclude<GuardEventsHandlerKebab[T], undefined>
  ) {
    this.eventListeners[evt]!.push(handler as any)
  }

  show() {
    this.visible = true
    this.render()
  }

  hide() {
    this.visible = false
    this.render()
  }
}
