// packages/native-js/src/components/AuthingGuard/index.tsx
import React from 'react'
import ReactDOM from 'react-dom'
import { AuthingGuard as ReactAuthingGuard } from 'react-components'
import {
  UserConfig,
  GuardScenes,
  LoginMethods,
  RegisterMethods,
  GuardEventsHandler,
  GuardEventsHandlerKebab,
} from 'react-components'
import 'react-components/lib/index.css'

export type {
  UserConfig,
  GuardScenes,
  LoginMethods,
  RegisterMethods,
  GuardEventsHandler,
  GuardEventsHandlerKebab,
}

export type EventListeners = {
  [key in keyof GuardEventsHandlerKebab]: Exclude<
    Required<GuardEventsHandlerKebab>[key],
    undefined
  >[]
}

export class AuthingGuard {
  constructor(private userPoolId: string, private config?: UserConfig) {
    if (config?.target) {
      this.render()
    }
  }

  static getGuardContainer(selector?: string | HTMLElement) {
    const defaultId = 'authing_guard_container'

    if (!selector) {
      let container = document.querySelector(`#${defaultId}`)
      if (!container) {
        container = document.createElement('div')
        container.id = defaultId
      }

      container.innerHTML = ''

      return container
    }

    if (typeof selector === 'string') {
      return document.querySelector(selector)
    }

    return selector
  }

  private eventListeners: EventListeners = {
    // 加载完成，userPool 配置和应用配置（如果有 appId）加载完成
    load: [],
    // 加载失败
    'load-error': [],
    // 用户登录成功
    login: [],
    // 用户登录失败
    'login-error': [],
    // 注册成功
    register: [],
    // 注册失败
    'register-error': [],
    // 忘记密码邮件发送成功
    'pwd-email-send': [],
    // 忘记密码邮件发送失败
    'pwd-email-send-error': [],
    // 忘记密码手机验证码发送成功
    'pwd-phone-send': [],
    // 忘记密码手机验证码发送失败
    'pwd-phone-send-error': [],
    // 重置密码成功
    'pwd-reset': [],
    // 重置密码失败
    'pwd-reset-error': [],
    // 表单关闭事件
    close: [],
  }

  static reactEvtMapNative: Record<
    keyof GuardEventsHandler,
    keyof GuardEventsHandlerKebab
  > = {
    onLoad: 'load',
    onLoadError: 'load-error',
    onLogin: 'login',
    onLoginError: 'login-error',
    onRegister: 'register',
    onRegisterError: 'register-error',
    onPwdEmailSend: 'pwd-email-send',
    onPwdEmailSendError: 'pwd-email-send-error',
    onPwdPhoneSend: 'pwd-phone-send',
    onPwdPhoneSendError: 'pwd-phone-send-error',
    onPwdReset: 'pwd-reset',
    onPwdResetError: 'pwd-reset-error',
    onClose: 'close',
  }

  render() {
    const evts: GuardEventsHandler = Object.entries(
      AuthingGuard.reactEvtMapNative
    ).reduce((acc, [reactEvt, nativeEvt]) => {
      return Object.assign({}, acc, {
        [reactEvt]: (...rest: any) => {
          this.eventListeners[nativeEvt].forEach((item: any) => {
            item(...rest)
          })
        },
      })
    }, {} as GuardEventsHandler)

    return ReactDOM.render(
      <ReactAuthingGuard
        {...evts}
        userPoolId={this.userPoolId}
        config={this.config}
      />,
      AuthingGuard.getGuardContainer(this.config?.target)
    )
  }

  on<T extends keyof GuardEventsHandlerKebab>(
    evt: T,
    handler: Exclude<GuardEventsHandlerKebab[T], undefined>
  ) {
    this.eventListeners[evt]!.push(handler as any)
  }

  show() {
    if (!this.config?.target) {
      this.render()
    }
  }
}

// packages/angular-components/projects/ng-ui-components/src/lib/AuthingGuard/authing-guard.component.ts
import {
  OnInit,
  Output,
  Component,
  EventEmitter,
  ViewEncapsulation,
  Input,
  OnChanges,
} from '@angular/core';
import {
  User,
  GuardMode,
  UserConfig,
  GuardScenes,
  AuthingGuard,
  LoginMethods,
  getAuthClient,
  CommonMessage,
  initAuthClient,
  RegisterMethods,
  GuardEventsHandler,
  AuthenticationClient,
  GuardEventsHandlerKebab,
  AuthenticationClientOptions,
} from '@authing/native-js-ui-components';

export type {
  User,
  UserConfig,
  CommonMessage,
  GuardEventsHandler,
  AuthenticationClient,
  GuardEventsHandlerKebab,
  AuthenticationClientOptions,
};

export {
  GuardMode,
  GuardScenes,
  LoginMethods,
  getAuthClient,
  initAuthClient,
  RegisterMethods,
};

@Component({
  selector: 'authing-guard',
  template: `<div id="authing_guard_container"></div>`,
  styles: [],
  styleUrls: ['./authing-guard.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class AuthingGuardComponent implements OnInit, OnChanges {
  constructor() {}

  guard: AuthingGuard;

  ngOnInit(): void {}

  ngOnChanges(v) {
    if (v.visible.currentValue) {
      this.guard?.show();
    } else {
      this.guard.hide();
    }
  }

  @Input() appId: string;
  @Input() visible?: boolean;
  @Input() tenantId?: string;
  @Input() config?: UserConfig;

  @Output() onLoad = new EventEmitter<
    Parameters<GuardEventsHandler['onLoad']>
  >();
  @Output() onLoadError = new EventEmitter<
    Parameters<GuardEventsHandler['onLoadError']>
  >();
  @Output() onLogin = new EventEmitter<
    Parameters<GuardEventsHandler['onLogin']>
  >();
  @Output() onLoginError = new EventEmitter<
    Parameters<GuardEventsHandler['onLoginError']>
  >();
  @Output() onRegister = new EventEmitter<
    Parameters<GuardEventsHandler['onRegister']>
  >();
  @Output() onRegisterError = new EventEmitter<
    Parameters<GuardEventsHandler['onRegisterError']>
  >();
  @Output() onPwdEmailSend = new EventEmitter<
    Parameters<GuardEventsHandler['onPwdEmailSend']>
  >();
  @Output() onPwdEmailSendError = new EventEmitter<
    Parameters<GuardEventsHandler['onPwdEmailSendError']>
  >();
  @Output() onPwdPhoneSend = new EventEmitter<
    Parameters<GuardEventsHandler['onPwdPhoneSend']>
  >();
  @Output() onPwdPhoneSendError = new EventEmitter<
    Parameters<GuardEventsHandler['onPwdPhoneSendError']>
  >();
  @Output() onPwdReset = new EventEmitter<
    Parameters<GuardEventsHandler['onPwdReset']>
  >();
  @Output() onPwdResetError = new EventEmitter<
    Parameters<GuardEventsHandler['onPwdResetError']>
  >();
  @Output() onClose = new EventEmitter<
    Parameters<GuardEventsHandler['onClose']>
  >();

  ngAfterViewInit() {
    const guard = new AuthingGuard(this.appId, this.config, this.tenantId);

    guard.on('load', (...rest) => this.onLoad.emit(rest));
    guard.on('load-error', (...rest) => this.onLoadError.emit(rest));
    guard.on('login', (...rest) => this.onLogin.emit(rest));
    guard.on('login-error', (...rest) => this.onLoginError.emit(rest));
    guard.on('register', (...rest) => this.onRegister.emit(rest));
    guard.on('register-error', (...rest) => this.onRegisterError.emit(rest));
    guard.on('pwd-email-send', (...rest) => this.onPwdEmailSend.emit(rest));
    guard.on('pwd-email-send-error', (...rest) =>
      this.onPwdEmailSendError.emit(rest)
    );
    guard.on('pwd-phone-send', (...rest) => this.onPwdPhoneSend.emit(rest));
    guard.on('pwd-phone-send-error', (...rest) =>
      this.onPwdPhoneSendError.emit(rest)
    );
    guard.on('pwd-reset', (...rest) => this.onPwdReset.emit(rest));
    guard.on('pwd-reset-error', (...rest) => this.onPwdResetError.emit(rest));
    guard.on('close', (...rest) => this.onClose.emit(rest));

    if (this.visible) {
      guard.show();
    }

    this.guard = guard;
  }
}
